#!/usr/bin/env bash

# install ansible on ubuntu
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

# pull ansible from repo
sudo ansible-pull -U https://github.com/skimura1/ansible
