- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
        - nvim
        - install
  tasks:
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/nvim.yml
