- name: install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: Install N
  community.general.npm:
    name: n
    global: true

- name: Install version of Node
  shell: n 14
  tags:
    - install
    - node
