- name: install deps
  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl"]
  tags:
    - install
    - nvim

- name: remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - nvim

- name: clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - nvim

- name: build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - nvim

- name: install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - nvim

- name: clone nvchad
  ansible.builtin.git:
    depth: 1
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
  tags:
    - install
    - nvim

